### ISSUE TITLE
When browsing reports, the web UI appears to use Basic Auth

### ISSUE THREAD

**Issue by benparsons** [matrix-org/rageshake#57]
When browsing reports, the web UI appears to use Basic Auth, which is not supported on Chrome. (It is still supported on Firefox.)

Do we have any suggestions for how to improve this? Is there a new workflow we're missing that does not require the web UI?

**Comment by t3chguy** [comment]
Basic auth works fine in my chrome, you might need to provide more detail.

**Comment by benparsons** [comment]
Interestingly, it works fine for me too. Customer may be seeing this issue https://bugs.chromium.org/p/chromium/issues/detail?id=623464 on some Chrome instances and not others. We'll get more info and update.

**Comment by pluex1** [comment]
I could verify that its not a problem with the rageshake itself. Its the missing basic authschemes in the policy for chrome and edge chromium. On Chrome/Chromium Browsers with no restrictions to authschemes i get the prompt for username and password.

**Comment by michaelkaye** [comment]
> When browsing reports, the web UI appears to use Basic Auth, which is not supported on Chrome. (It is still supported on Firefox.)
> 
> Do we have any suggestions for how to improve this? Is there a new workflow we're missing that does not require the web UI?

I'd suggest deploying a proxy handling auth in front of rageshake (eg integrate to a sso via oauth2) rather than directly exposing the basic auth to browsers; I don't think rageshakes should extend to add a more featureful authentication option internally.

Basic auth is probably good enough for single-developer use cases so we shouldn't junk it outright.
